config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created'
    else
      render :new
    end
  end

  def edit; end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit flat:</h1>
  <%= render 'form' %>
</div>

app/views/flats/index.html.erb
<div class="container p-5">
  <div class="row">
    <h1>All flats</h1>
  </div>
  <div class="row">
    <p>There are <%= @flats.count %> flats available.</p>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="card-group col-4 p-1">
      <div class="card">
        <img src="https://source.unsplash.com/random/324x200">
        <div class="card-body text-center border-bottom">
          <h5 class="card-title"><%= link_to flat.name, flat_path(flat)%></h5>
          <p class="card-text small"><%= flat.address %></p>
          <div class="row d-flex justify-content-between">
            <p class="card-text mx-3"><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></p>
            <p class="card-text mx-3">€ <%= flat.price_per_night %></p>
          </div>
        </div>
        <div class="card-actions p-3">
          <%= link_to 'More Info', flat_path(flat), class: 'text-primary' %>
          <%= link_to 'Edit', edit_flat_path(flat), class: 'text-warning' %>
          <%= link_to 'Remove', flat_path(flat), method: :delete, class: 'text-danger' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new flat</h1>
  <%= render 'form' %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>
  <h5><%= @flat.address %></h5>
  <h3>A bit more about this flat... </h3>
    <p><%= @flat.description %></p>
  <h3>Details:</h3>
    <p class="card-text mx-3"><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %></p>
    <p class="card-text mx-3">€ <%= @flat.price_per_night %></p>
    <%= link_to 'Back', flats_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Simple Airbnb', flats_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary ml-2' %>
          </form>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>